function blockswithwithdrawalframes2 = import_csv(filename, dataLines)
%IMPORTFILE Import data from a text file
%  BLOCKSWITHWITHDRAWALFRAMES2 = IMPORTFILE(FILENAME) reads data from
%  text file FILENAME for the default selection.  Returns the data as a
%  table.
%
%  BLOCKSWITHWITHDRAWALFRAMES2 = IMPORTFILE(FILE, DATALINES) reads data
%  for the specified row interval(s) of text file FILENAME. Specify
%  DATALINES as a positive scalar integer or a N-by-2 array of positive
%  scalar integers for dis-contiguous row intervals.
%
%  Example:
%  blockswithwithdrawalframes2 = importfile("C:\Users\acuna\Repositories\yolov7\blocks_with_withdrawal_frames.csv", [2, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 16-Feb-2024 22:25:46

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [2, Inf];
end

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 4);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["Label", "Block_Start", "Block_End", "Withdrawal_Frame"];
opts.VariableTypes = ["categorical", "double", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, "Label", "EmptyFieldRule", "auto");

% Import the data
blockswithwithdrawalframes2 = readtable(filename, opts);

end